{"trial_id": "0001", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 5, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_0", "default": null, "conditions": [], "min_value": 16, "max_value": 128, "step": 16, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_1", "default": null, "conditions": [], "min_value": 16, "max_value": 128, "step": 16, "sampling": "linear"}}], "values": {"num_layers": 3, "units_0": 32, "units_1": 16, "tuner/epochs": 3, "tuner/initial_epoch": 0, "tuner/bracket": 2, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"c:\\ProgramData\\anaconda3\\envs\\ai\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\ProgramData\\anaconda3\\envs\\ai\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\ProgramData\\anaconda3\\envs\\ai\\lib\\site-packages\\keras_tuner\\src\\tuners\\hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\ProgramData\\anaconda3\\envs\\ai\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"c:\\ProgramData\\anaconda3\\envs\\ai\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 232, in _build_and_fit_model\n    model = self._try_build(hp)\n  File \"c:\\ProgramData\\anaconda3\\envs\\ai\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 164, in _try_build\n    model = self._build_hypermodel(hp)\n  File \"c:\\ProgramData\\anaconda3\\envs\\ai\\lib\\site-packages\\keras_tuner\\src\\tuners\\hyperband.py\", line 430, in _build_hypermodel\n    model = super()._build_hypermodel(hp)\n  File \"c:\\ProgramData\\anaconda3\\envs\\ai\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 155, in _build_hypermodel\n    model = self.hypermodel.build(hp)\n  File \"C:\\Users\\AERO\\AppData\\Local\\Temp\\ipykernel_18788\\3373725182.py\", line 9, in build_simple_rnn\n    model.add(SimpleRNN(\n  File \"c:\\ProgramData\\anaconda3\\envs\\ai\\lib\\site-packages\\keras\\layers\\rnn\\simple_rnn.py\", line 397, in __init__\n    super().__init__(\n  File \"c:\\ProgramData\\anaconda3\\envs\\ai\\lib\\site-packages\\keras\\layers\\rnn\\base_rnn.py\", line 268, in __init__\n    super().__init__(**kwargs)\n  File \"c:\\ProgramData\\anaconda3\\envs\\ai\\lib\\site-packages\\tensorflow\\python\\trackable\\base.py\", line 205, in _method_wrapper\n    result = method(self, *args, **kwargs)\n  File \"c:\\ProgramData\\anaconda3\\envs\\ai\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 447, in __init__\n    batch_input_shape = (batch_size,) + tuple(kwargs[\"input_shape\"])\nTypeError: 'NoneType' object is not iterable\n"}